---
# vars file for role-kibana
elasticsearch_rpm_key: http://packages.elastic.co/GPG-KEY-elasticsearch
kibana_version: 4.4
distribution_type: centos
elasticsearch_host: localhost
kibana_repo_name: kibana.repo
kibana_pkg_name: kibana
kibana_fileconf_name: kibana.yml
kibana_service_name: kibana
kibana_directorylogpath_name: /var/log/kibana-rotate
kibana_filelogpath_name: "{{kibana_directorylogpath_name}}/kibana.log"
