---
# vars file for role-logstash
logstash_version: 2.2
elasticsearch_rpm_key: http://packages.elastic.co/GPG-KEY-elasticsearch
elasticsearch_host: localhost
elasticsearch_port: 9200
logstash_repo_name: logstash.repo
logstash_pkg_name: logstash
logstash_service_name: logstash
logstash_fileconf_name: 02-beats-input.conf
logstash_syslog_filter: 10-syslog-filter.conf
logstash_elasticsearch_output: 30-elasticsearch-output.conf
logstash_logconf_name: logging.yml
logstash_forwarder_cert: /etc/pki/tls/certs/logstash-forwarder.crt
logstash_forwarder_key: /etc/pki/tls/private/logstash-forwarder.key
logstash_service: logstash.service
